services:
  mongo:
    image: mongo:latest
    container_name: mongo_dev
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database

  backend:
    image: backend_dev
    ports:
      - 3001:3001
    build: 
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://the_username:the_password@mongo:27017/the_database
      - TEST_MONGO_URI=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - mongo

  frontend:
    image: frontend_dev
    ports:
      - 5173:5173
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - BACKEND_URL=http://backend:3001
    depends_on:
      - backend
    
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - frontend
      - backend

volumes:
  mongo: